# -*- coding: utf-8 -*-
"""Restenosis_risk_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwGpC1rhkVKZi3sWdc-yKm2VxVsgMFUM

Notebook to run the model developed for the study:

### "MACHINE LEARNING TO PREDICT STENT RESTENOSIS BASED ON DAILY DEMOGRAPHIC, CLINICAL AND ANGIOGRAPHIC CHARACTERISTICS"

In order to run the notebook:
- Write the inputs in the next cell. In case one of the features is not available, keep the values that are already written.
- Click on "Runtime -> Run all". Wait the notebook to run all cells. Check the results at the end of it.
"""

# Data inputs
diabetes = 1
vessels_gt2 = 0
thrombust_post_pci = 0
timi_post_pci = 3
abnormal_cholesterol = 0
abnormal_platelets = 0

import os
if os.path.exists('./finalized_model.sav') == False:
  !wget -nv https://raw.githubusercontent.com/IA-Cardiologia-husa/Restenosis/master/models/finalized_model.sav
    
if os.path.exists('./probs.csv') == False:
  !wget -nv https://raw.githubusercontent.com/IA-Cardiologia-husa/Restenosis/master/models/probs.csv
   
if os.path.exists('./funcs_bokeh.py') == False:
  !wget -nv https://raw.githubusercontent.com/IA-Cardiologia-husa/Restenosis/master/calculator/funcs_bokeh.py

from funcs_bokeh import *
model = pickle.load(open('finalized_model.sav', 'rb'))
model = model.named_steps['clf']
X = np.array([diabetes, vessels_gt2, thrombust_post_pci, timi_post_pci,
              abnormal_cholesterol, abnormal_platelets]).reshape(1,6)
proba = model.predict_proba(X)

data = pd.read_csv('probs.csv', sep = ';')
fpr1, tpr1, prec1, rec1, spe1, npv1 = gracia_curves(data)
PREC, REC, SPE, NPV = point_scores(data, proba[0][1])

"""### PREDICTING PROBABILITY OF RESTENOSIS"""

print('GRACIA-3 restenosis risk score: %2f' % (proba[0][1]))
print('For this score, the  model gives the next metrics: ')
print('Specifity = %2f' % (SPE))
print('Sensitivity = %2f' % (REC))
print('Precision = %2f' % (PREC))
print('Negative Predictive Value = %2f' % (NPV))

"""### PLOTTING YOUR POINT OVER THE GRACIA-3 MODEL ROC CURVE"""

thresholds_pr = [0, 0.18, 0.56, 0.81,1]
thresholds_fpr = [0, 0.018, 0.14, 0.466,1]
thresholds_npv = [0, 0.53, 0.86, 0.98,1]
colors = ["red", "orange", "yellow", "green"]

output_notebook()
fig1 = figure_bokeh('ROC', thresholds=thresholds_fpr, x_label = 'FPR', y_label = 'TPR',
             x = fpr1, y = tpr1, x_p = 1-SPE, y_p = REC, colors = colors, legend_pos = 'bottom_right')
fig2 = figure_bokeh('P-R', thresholds=thresholds_pr, x_label = 'REC', y_label = 'PREC',
             x = rec1, y = prec1, x_p = REC, y_p = PREC, colors = colors, legend_pos = 'top_right')
fig3 = figure_bokeh('NPV-SPE', thresholds=thresholds_npv, x_label = 'SPE', y_label = 'NPV',
             x = spe1, y = npv1, x_p = SPE, y_p = NPV, colors = colors[::-1], legend_pos = 'bottom_right', range_y = (0.85,1))
show(column(fig1, fig2, fig3))

